nomes = [
    "Alessandro Paz Justino",
    "Daiana Salles Cavalcanti",
    "Larissa Almeida Miranda",
    "Antonio Barros Gonçalves",
    "Giovane Campos Caetano",
    "Estela Dutra Brito",
    "Zilda Alencar Sato",
    "Iago Antunes Câmara",
    "Manuel Espíndola Brito",
    "Osvaldo Vale Pinheiro",
    "Amanda Delchiaro dos Santos",
    "Érica Sato Fontes",
    "Esther Couto da Fonseca",
    "Leonardo Barbosa Quadros",
    "Vítor Nazário Yoshimura",
    "Fábio Braga Ramos",
    "Milena Lacerda da Conceição",
    "Natália Yoshimura Lópes",
    "Rosana Pires Luz",
    "Thiago Reis de Oliveira",
    "Tadeu Guerra Bosco",
    "Erasmo Bitencourt de Almeida",
    "Sérgio Barros Brito",
    "Escobar Macedo Zanetti",
    "Renato Belluci Bueno",
    "Norberto Paiva Dias",
    "Carlos Quadros Ventura",
    "Conrado Fagundes Nakata",
    "Cláudio Bastos Bonfim",
    "Cleiton Paschoal Linhares",
    "Émerson Rosa Hamamura",
    "Edgar Yoshimura Velho",
    "Thiago Bitencourt Fernandes",
    "Iago Garcia Corrêa",
    "Manuel Madruga Vila",
    "Gustavo Nogueira Pinho",
    "Bernardo Hamada Ximenes",
    "Arnaldo Justino de Castro",
    "Breno Delgado de Albuquerque",
    "Sebastião Leite Antunes",
    "Daiana Salles Cavalcanti",
    "Larissa Almeida Miranda",
    "Estela Dutra Brito",
    "Zilda Alencar Sato",
    "Amanda Delchiaro dos Santos",
    "Érica Sato Fontes",
    "Esther Couto da Fonseca",
    "Milena Lacerda da Conceição",
    "Natália Yoshimura Lópes",
    "Rosana Pires Luz",
    "Miriam Aguiar Esteves",
    "Ana Lourenço Paiva",
    "Magali Araújo de Ávila",
    "Rosa Linhares Furtado",
    "Shirlei Queiroz Hamada",
    "Alice Paim Linhares",
    "Iara Padilha Bastos",
    "Olga Barreto Pimentel",
    "Darcy Guimarães Salgado",
    "Sônia Delgado do Vale",
]